shfmt processing

diff --git a/mkuird b/mkuird
--- a/mkuird
+++ b/mkuird
@@ -1,18 +1,18 @@
 #!/bin/bash
 echo $a
-if [  $1 ] ; then 
+if [ $1 ]; then
 	CFG=$1
 else
 	#default uird for legacy
 	CFG=legacy
 fi
 
-if ! [ -f ./configs/uird_configs/$CFG ] ; then 
+if ! [ -f ./configs/uird_configs/$CFG ]; then
 	echo "./configs/uird_configs/$CFG is not exist"
 	exit 1
-fi  
+fi
 
-echo $date > ./not_found.log
+echo $date >./not_found.log
 cd dracut/modules.d
 ln -s ../../modules.d/* ../modules.d/ 2>/dev/null
 cd ../..
@@ -22,35 +22,33 @@ kernelmods="loop cryptoloop cbc zram aes-generic aes-i586 aes-x86_64 pata_acpi a
                        hid-generic sr_mod sd_mod scsi_mod jbd jbd2 lockd evdev sunrpc lz4 af_packet dm-crypt nbd"
 
 FS=''
-for mod in $filesystems ; do
-  if /sbin/modinfo $mod >/dev/null ;then
-    FS="$FS $mod"
-  else
-    echo "kernel module: $mod not found" >> ./not_found.log
-  fi
- done
+for mod in $filesystems; do
+	if /sbin/modinfo $mod >/dev/null; then
+		FS="$FS $mod"
+	else
+		echo "kernel module: $mod not found" >>./not_found.log
+	fi
+done
 
 KM="=drivers/ide =drivers/ata  =drivers/net/ethernet =drivers/usb/storage =drivers/usb/host =fs/nfs"
-for mod in $kernelmods ; do
-  if /sbin/modinfo $mod >/dev/null ;then
-    KM="$KM $mod"
-  else
-    echo "kernel module: $mod not found" >> ./not_found.log
-  fi
- done
+for mod in $kernelmods; do
+	if /sbin/modinfo $mod >/dev/null; then
+		KM="$KM $mod"
+	else
+		echo "kernel module: $mod not found" >>./not_found.log
+	fi
+done
 
- 
-./dracut/dracut.sh -l -N --strip -f -m "base uird uird-network ntfs kernel-modules crypt"  \
-    	-d "$KM" \
-        --filesystems "$FS"  \
-        -i initrd / \
-        -i configs / \
-        --kernel-cmdline "uird.basecfg=/uird_configs/$CFG" \
-        -c dracut.conf -v -M uird.$CFG.cpio.xz $(uname -r)  >dracut_magos.log 2>&1
-
+./dracut/dracut.sh -l -N --strip -f -m "base uird uird-network ntfs kernel-modules crypt" \
+	-d "$KM" \
+	--filesystems "$FS" \
+	-i initrd / \
+	-i configs / \
+	--kernel-cmdline "uird.basecfg=/uird_configs/$CFG" \
+	-c dracut.conf -v -M uird.$CFG.cpio.xz $(uname -r) >dracut_magos.log 2>&1
 
 [ $2 ] && mv uird.$CFG.cpio.xz "$2"
 
-#./dracut/dracut.sh -l -N --strip -f -m "base uird uird-network ntfs kernel-modules kernel-network-modules" 
+#./dracut/dracut.sh -l -N --strip -f -m "base uird uird-network ntfs kernel-modules kernel-network-modules"
 #        --kernel-cmdline "uird.from=/MagOS,/MagOS-Data uird.ro=*.xzm,*.rom,*.rom.enc,*.pfs,*.sfs uird.rw=*.rwm,*.rwm.enc uird.cp=*.xzm.cp,*/rootcopy uird.load=/base/,/modules/,rootcopy uird.machines=/MagOS-Data/machines uird.config=MagOS.ini" \
 #        -c dracut.conf -v -M uird.magos.cpio.xz 3.19.4-desktop586-2.mga5 >dracut_magos.log 2>&1
